name:                TPFinal
version:             0.1.0.0
github:              "emmanuelmess/SetsOperationsInterface"
license:             BSD3
author:              "Facundo Emmanuel Messulam"
copyright:           "2021-2022 Facundo Emmanuel Messulam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TP4#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- boxes
- containers
- mtl
- directory
- haskeline
- split
default-extensions:
- GADTs
- StandaloneDeriving
- PatternSynonyms
- FlexibleInstances
- TupleSections

library:
  source-dirs: 
  - src 
  - src/algebra
  - src/relation

executables:
  TPFinal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -funfolding-use-threshold=16
    - -O2
    - -optc-O3
    dependencies:
    - TPFinal

tests:
  unit-test:
    main: Test.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - TPFinal
      - QuickCheck
